<?php
/**
 * FahrzeugscheinApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MMMint.ai - Registration Recognition API
 *
 * ## General Information   This API is hosted by MMM Intelligence UG (haftungsbeschränkt) providing smart solutions, [imprint](https://mmmint.ai/impressum).   ## Support   For support reach out to [support@mmmint.ai](mailto:support@mmmint.ai). For usage of the registration recognition API an **APIKey** (`access_token`) is required.   ## Usage Information   1. In order to use the registration recognition API you start by submitting an image via file upload, or with a publicly accessible image of the registration, using a `POST` to `/fahrzeugschein`.   1. The asynchronous processing of the the recognition can be checked using the `/fahrzeugschein/status/{sessionId}` resource.   1. After the status is `finished`, the recognized data can be retrieved using `/fahrzeugschein/{id}` resource.   1. The bounding boxes and associated cropped images can be retrieved using the `/detection` resources.   1. To retrieve all sessions for the submitted registration use the `/session` resource. The sessions will also indicate the status of all submissions.   ## Encryption Information   The provided service is hosted in german datacenters. Submitted data is encrypted in transit and at rest. The submitted date can only be accessed using the used APIKey.   ## Security Information   In case of a leaked APIKey reach out to us immediately. All submitted data can be deleted upon request within 30 days upon notice.
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * FahrzeugscheinApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FahrzeugscheinApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for correctFahrzeugscheinFahrzeugscheinSessionIdPut
     *
     * Correct Fahrzeugschein.
     *
     */
    public function testCorrectFahrzeugscheinFahrzeugscheinSessionIdPut()
    {
    }

    /**
     * Test case for correctFahrzeugscheinFahrzeugscheinSessionIdPut_0
     *
     * Correct Fahrzeugschein.
     *
     */
    public function testCorrectFahrzeugscheinFahrzeugscheinSessionIdPut0()
    {
    }

    /**
     * Test case for deleteFahrzeugscheinFahrzeugscheinSessionIdDelete
     *
     * Delete Fahrzeugschein.
     *
     */
    public function testDeleteFahrzeugscheinFahrzeugscheinSessionIdDelete()
    {
    }

    /**
     * Test case for deleteFahrzeugscheinFahrzeugscheinSessionIdDelete_0
     *
     * Delete Fahrzeugschein.
     *
     */
    public function testDeleteFahrzeugscheinFahrzeugscheinSessionIdDelete0()
    {
    }

    /**
     * Test case for getResultFahrzeugscheinSessionIdGet
     *
     * Get Result.
     *
     */
    public function testGetResultFahrzeugscheinSessionIdGet()
    {
    }

    /**
     * Test case for getResultFahrzeugscheinSessionIdGet_0
     *
     * Get Result.
     *
     */
    public function testGetResultFahrzeugscheinSessionIdGet0()
    {
    }

    /**
     * Test case for getResultXmlFahrzeugscheinSessionIdXmlGet
     *
     * Get Result Xml.
     *
     */
    public function testGetResultXmlFahrzeugscheinSessionIdXmlGet()
    {
    }

    /**
     * Test case for getResultXmlFahrzeugscheinSessionIdXmlGet_0
     *
     * Get Result Xml.
     *
     */
    public function testGetResultXmlFahrzeugscheinSessionIdXmlGet0()
    {
    }

    /**
     * Test case for getResultXmlSasTokenFahrzeugscheinSessionIdXmlSastokenPost
     *
     * Get Result Xml Sas Token.
     *
     */
    public function testGetResultXmlSasTokenFahrzeugscheinSessionIdXmlSastokenPost()
    {
    }

    /**
     * Test case for getResultXmlSasTokenFahrzeugscheinSessionIdXmlSastokenPost_0
     *
     * Get Result Xml Sas Token.
     *
     */
    public function testGetResultXmlSasTokenFahrzeugscheinSessionIdXmlSastokenPost0()
    {
    }

    /**
     * Test case for getStatusFahrzeugscheinStatusSessionIdGet
     *
     * Get Status.
     *
     */
    public function testGetStatusFahrzeugscheinStatusSessionIdGet()
    {
    }

    /**
     * Test case for getStatusFahrzeugscheinStatusSessionIdGet_0
     *
     * Get Status.
     *
     */
    public function testGetStatusFahrzeugscheinStatusSessionIdGet0()
    {
    }

    /**
     * Test case for submitFahrzeugscheinFileFahrzeugscheinPost
     *
     * Submit Fahrzeugschein File.
     *
     */
    public function testSubmitFahrzeugscheinFileFahrzeugscheinPost()
    {
    }

    /**
     * Test case for submitFahrzeugscheinFileFahrzeugscheinPost_0
     *
     * Submit Fahrzeugschein File.
     *
     */
    public function testSubmitFahrzeugscheinFileFahrzeugscheinPost0()
    {
    }

    /**
     * Test case for submitFahrzeugscheinUrlFahrzeugscheinUrlPost
     *
     * Submit Fahrzeugschein Url.
     *
     */
    public function testSubmitFahrzeugscheinUrlFahrzeugscheinUrlPost()
    {
    }

    /**
     * Test case for submitFahrzeugscheinUrlFahrzeugscheinUrlPost_0
     *
     * Submit Fahrzeugschein Url.
     *
     */
    public function testSubmitFahrzeugscheinUrlFahrzeugscheinUrlPost0()
    {
    }
}
